OBJECT_CUBE = 0
OBJECT_CAMERA = 1
OBJECT_SKY = 2
OBJECT_LEAF = 4
OBJECT_BRANCH = 5

PIPELINE_SKY = 0
PIPELINE_3D = 1

EVENT_NEW = 1
EVENT_DEL = 2


BRANCH_TOP_RADIUS = 0.9
BRANCH_HEIGHT = 1

BRANCH_SPLIT_Y = 0.75
BRANCH_SPLIT_Z = 0.7
BRANCH_SPLIT_RADIUS = 0.7
BRANCH_SPLIT_X_ROTATION = 30

MAX_DEPTH = 10

SPLIT_CHANCE = 0.25
LEAF_GROWING_MAX_RADIUS = 0.2
MIN_EXTEND_RADIUS = 0.05